### ISSUE TITLE
Error	2	error LNK1104: cannot open file 'libboost_system-vc120-mt-1_57.lib'	D:\SERVER\build\src\server\worldserver\LINK	worldserver

### ISSUE THREAD

**Issue by aramiss** [NoffearrDeathProjecT/DeathCore_6.x#5]
Error	2	error LNK1104: cannot open file 'libboost_system-vc120-mt-1_57.lib'	D:\SERVER\build\src\server\worldserver\LINK	worldserver

**Comment by Noffearr** [comment]
Update your version of boost and their libraries.
