### ISSUE TITLE
Compile - Error in Linux

### ISSUE THREAD

**Issue by Dude100** [NoffearrDeathProjecT/DeathCore_6.x#6]
http://pastebin.com/w4tzXqQ4

Linux debian 3.2.0-4-amd64 #1 SMP Debian 3.2.65-1+deb7u1 x86_64 GNU/Linux

**Comment by Noffearr** [comment]
yes friend I know this not compiling on Linux - https://travis-ci.org/NoffearrDeathProjecT/DeathCore_6.x - more windowns compiles normally! Later I will fix this - thank you for reporting!

**Comment by Dude100** [comment]
Ty Noffearr

**Comment by Noffearr** [comment]
Fixed Error in https://github.com/NoffearrDeathProjecT/DeathCore_6.x/commit/b8bba4a73cebca220c5ff0d1233b575f4b162ae4!

Thank you for reporting!
